name: unit-fast
on:
  workflow_call:
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: setup bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2
        with:
          bun-version: 'latest'
      - name: install dependencies
        run: bun i
      - name: run fast unit tests
        run: >
          bun vitest run --reporter=verbose --no-coverage
          test/spec/01_kat.test.ts
          test/spec/02_intermediate.test.ts
          test/spec/11_base.test.ts
          test/spec/12_chacha20.test.ts
          test/spec/13_hmac.test.ts
          test/spec/14_padding.test.ts
          test/spec/15_pbkdf2.test.ts
          test/spec/16_serpent.test.ts
          test/spec/17_sha256.test.ts
          test/spec/18_sha512.test.ts
          test/spec/19_sha3.test.ts
          test/spec/20_uuid.test.ts
